name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important!

      - name: Install dependencies
        run: |
          # If you have dependencies, install them here
          # For example, npm install
          echo "No dependencies to install"

      - name: Build the site
        run: |
          # If you have a build script, run it here
          # For example, npm run build
          echo "No build script to run"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust to your publish directory
          force_orphan: true  # Creates a new commit history on gh-pages branch
