name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensure credentials are not persisted

      # If you have dependencies to install, include this step
      # - name: Install dependencies
      #   run: |
      #     npm install

      # If you have a build script, include this step
      # - name: Build the site
      #   run: |
      #     npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust to your publish directory
          force_orphan: true  # Creates a new commit history on gh-pages branch
